export default Object.freeze({
    LISTING_SCREEN: "ListingScreen",
    LISTING_EDIT_SCREEN: "ListingEditScreen",
    LISTING_DETAILS_SCREEN: "ListingDetailsScreen",
    MESSAGES_SCREEN: "MessagesScreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "RegisterScreen",
    ACCOUNT_SCREEN: "AccountScreen",
    WELCOME_SCREEN: "WelcomeScreen",
    ACCOUNT_NAVIGATOR: "Account",
    BASKET_SCREEN: "BasketScreen",
    HOME_NAVIGATOR: "Home",
    CATEGORIES_SCREEN: "CategoriesScreen",
    FORGOT_PASSWORD_SCREEN: "ForgotPasswordScreen",
    ACCOUNT_EDIT_SCREEN: "AccountEditScreen",
    ORDER_SCREEN: "OrderScreen",
    SALES_SCREEN: "SalesScreen",
    ADMINISTRATORS_SCREEN: "AdministratorsScreen",
});
